name: Pelimovies
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.18.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.0.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.1.1
  carousel_slider: ^4.1.1
  google_fonts: ^6.1.0
  custom_refresh_indicator: ^2.0.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.0
  sqflite: ^2.2.2
  path: ^1.8.2
  mason: ^0.1.0-dev.47
  webview_flutter: ^4.4.1
  flutter_pdfview: ^1.3.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/pdf/
    - shorebird.yaml
